# Generated by Django 3.0.3 on 2020-10-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=32, verbose_name='主机名'),
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=2)),
                ('pd_type', models.CharField(max_length=16)),
                ('capacity', models.FloatField(default=0)),
                ('model', models.CharField(max_length=256)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Server')),
            ],
            options={
                'db_table': 'Disk',
            },
        ),
    ]
