# Generated by Django 3.0.3 on 2020-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201023_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update',
            field=models.DateField(blank=True, null=True, verbose_name='上次更新'),
        ),
    ]
