# Generated by Django 3.0.3 on 2020-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_server_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('d', models.DateField()),
            ],
            options={
                'db_table': 'DateTest',
            },
        ),
    ]
