# Generated by Django 3.0.3 on 2020-10-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_datetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.CharField(max_length=16, verbose_name='容量'),
        ),
    ]
